#!/opt/homebrew/bin/bash

OPENSCAD="/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"
README="README.md"

cat << EOF > $README
# Preview images

Generated by \`generate_readme.sh\` on `date`.

EOF

# get all the file names
readarray -t FILES <<<"$(ls */*.scad)"

# loop through the array
for FILE in "${FILES[@]}"
do
  NAME=`basename "$FILE" .scad`
  echo "processing $FILE '$NAME'"
  
  # print a H2 title of the file name
  echo "## \`$FILE\`" >> $README

  # print a link to the source code
  echo >> $README
  echo "source: [${FILE}](${FILE})" >> $README
  echo >> $README

  # print an image tag
  echo "![$NAME](images/$NAME.png \"$NAME\")" >> $README
  # a blank line to trigger a markdown section
  echo "" >> $README

  "$OPENSCAD" --colorscheme "Tomorrow Night" --projection o --viewall --autocenter -o "images/${NAME}.png" "$FILE"

  echo
done

